# Generated by Django 5.1.1 on 2024-12-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telcox_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dato_usado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='minuto_usuado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
