# Generated by Django 5.1.1 on 2024-12-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telcox_api', '0002_alter_cliente_dato_usado_alter_cliente_minuto_usuado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='minuto_usuado',
            new_name='minuto_usado',
        ),
    ]
