# Generated by Django 5.1.1 on 2024-12-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telcox_api', '0003_rename_minuto_usuado_cliente_minuto_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mes',
            field=models.CharField(default='Enero', max_length=50),
        ),
    ]
